# Generated by Django 4.2 on 2024-08-08 14:12

from django.db import migrations
import multipleselectionfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='areas_of_interest',
            field=multipleselectionfield.db.fields.MultipleSelectionField(blank=True, choices=[('Administração', 'Administração'), ('Contabilidade', 'Contabilidade'), ('Direito', 'Direito'), ('Economia', 'Economia'), ('Estética', 'Estetica'), ('Finanças', 'Finanças'), ('Gastronomia', 'Gastronomia'), ('Humanidades', 'Humanidades'), ('Linguagens', 'Linguagens'), ('Massoterapia', 'Massoterapia'), ('Saúde', 'Saúde'), ('Tecnologia da Informação', 'Tecnologia da Informação')], max_length=1000, null=True, verbose_name='Áreas de Interesse'),
        ),
    ]
