# Generated by Django 4.2 on 2025-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
    ]
